name: CuSe
favicon: null
layout_spectrum: 0.2725564
typography_spectrum: 0.202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acd8d9'
    - '#87827c'
    - '#f5e15a'
    - '#5c5753'
    - '#292826'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
