name: CuSe
favicon: null
layout_spectrum: 0
typography_spectrum: 0.18363
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acd8d9'
    - '#87827c'
    - '#f5e15a'
    - '#5c5753'
    - '#292826'
  brandStrength: 0.6875
  lightness: 0.2694235
  saturation: 0.8276942
  rhythmicContrast: 0.1259398
purpose: []
