layout_spectrum: 0.2725564
favicon: null
name: CuSe
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.6875
  lightness: 0.2694235
  saturation: 0.8276942
  rhythmicContrast: 0.1259398
  brandColors:
    - '#acd8d9'
    - '#87827c'
    - '#f5e15a'
    - '#5c5753'
    - '#292826'
typography_spectrum: 0.202
