layout_spectrum: 0.2725564
typography_spectrum: 0
color:
  lightness: 0.9598997
  brandStrength: 0.4968672
  saturation: 0.2362155
  rhythmicContrast: 0.4379699
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: CuSe
